import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

export const exportCSV = (data: any[]) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(workbook, worksheet, "Orders");
  XLSX.writeFile(workbook, "orders.csv");
};

export const exportExcel = (data: any[]) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(workbook, worksheet, "Orders");
  XLSX.writeFile(workbook, "orders.xlsx");
};

export const exportPDF = (
  data: any[],
  mode: "light" | "dark" = "light"
) => {
  const doc = new jsPDF();

  // =========================
  // DARK BACKGROUND
  // =========================
  if (mode === "dark") {
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 297, "F");
  }

  // =========================
  // TITLE
  // =========================
  doc.setFontSize(24);

  if (mode === "dark") {
    doc.setTextColor(255, 255, 255);
  } else {
    doc.setTextColor(15, 23, 42);
  }

  doc.text("StorePulse Analytics Report", 14, 20);

  doc.setFontSize(10);

  if (mode === "dark") {
    doc.setTextColor(203, 213, 225);
  } else {
    doc.setTextColor(100, 116, 139);
  }

  doc.text(
    `Generated: ${new Date().toLocaleDateString()}`,
    14,
    28
  );

  // =========================
  // KPI SECTION
  // =========================
  if (mode === "dark") {
    // Revenue
    doc.setFillColor(14, 165, 233);
    doc.roundedRect(14, 38, 42, 20, 3, 3, "F");

    // Users
    doc.setFillColor(6, 182, 212);
    doc.roundedRect(62, 38, 42, 20, 3, 3, "F");

    // Customers
    doc.setFillColor(34, 197, 94);
    doc.roundedRect(110, 38, 42, 20, 3, 3, "F");

    // Growth
    doc.setFillColor(249, 115, 22);
    doc.roundedRect(158, 38, 38, 20, 3, 3, "F");

    doc.setTextColor(255, 255, 255);

    doc.setFontSize(8);

    doc.text("Revenue", 18, 45);
    doc.text("Users", 68, 45);
    doc.text("Customers", 114, 45);
    doc.text("Growth", 163, 45);

    doc.setFontSize(12);

    doc.text("$1.24M", 18, 53);
    doc.text("48.2K", 68, 53);
    doc.text("1820", 114, 53);
    doc.text("24.6%", 163, 53);
  } else {
    doc.setFillColor(243, 244, 246);
    doc.roundedRect(14, 38, 182, 20, 3, 3, "F");

    doc.setTextColor(15, 23, 42);

    doc.setFontSize(11);

    doc.text(
      "Revenue: $1.24M   •   Users: 48.2K   •   Customers: 1820   •   Growth: 24.6%",
      18,
      50
    );
  }

  // =========================
  // TABLE
  // =========================
  autoTable(doc, {
    startY: 70,

    head: [["Order ID", "Customer", "Date", "Status", "Amount"]],

    body: data.map((o) => [
      o.id,
      o.customer,
      o.date,
      o.status,
      `$${o.amount}`,
    ]),

    theme: "striped",

    headStyles:
      mode === "dark"
        ? {
            fillColor: [6, 182, 212],
            textColor: [255, 255, 255],
            fontStyle: "bold",
          }
        : {
            fillColor: [37, 99, 235],
            textColor: [255, 255, 255],
            fontStyle: "bold",
          },

    bodyStyles:
      mode === "dark"
        ? {
            fillColor: [15, 23, 42],
            textColor: [255, 255, 255],
          }
        : {
            textColor: [15, 23, 42],
          },

    alternateRowStyles:
      mode === "dark"
        ? {
            fillColor: [30, 41, 59],
          }
        : {
            fillColor: [248, 250, 252],
          },

    styles: {
      lineWidth: 0.1,
    },
  });

  // =========================
  // FOOTER
  // =========================
  const finalY =
    (doc as any).lastAutoTable?.finalY || 70;

  doc.setFontSize(8);

  if (mode === "dark") {
    doc.setTextColor(148, 163, 184);
  } else {
    doc.setTextColor(107, 114, 128);
  }

  doc.text(
    "Generated by StorePulse Dashboard",
    14,
    finalY + 15
  );

  // =========================
  // SAVE
  // =========================
  doc.save(
    mode === "dark"
      ? "storepulse-dark-report.pdf"
      : "storepulse-light-report.pdf"
  );
};

// =========================
// PRINT
// =========================
export const printLight = () => {
  window.print();
};